### ISSUE TITLE
Cannot read property 'registerForEvent' of null

### ISSUE THREAD

**Issue by aikssen** [OfficeDev/Office-Add-in-Dialog-API-Simple-Example#3]
When is triggered the pop-up action, not the iFrame version. The new window lunch the error `Cannot read property 'registerForEvent' of null`. This error interrupt all the functioning of the dialog window.
This error also appears on Excel add-ins, and prevent to sent back the information to the parent task pane window.

Some interesting fact, is that this error appears as soon as the `<script>` tag is added to the pop-up html, without even put any additional line of code.

Here is the trace:
```
word-web-16.00.js:21 Uncaught TypeError: Cannot read property 'registerForEvent' of null
    at OSF.DDA.WAC.Delegate.registerEventAsync (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:105449)
    at e.(anonymous function) (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:67767)
    at Object.value [as addHandlerAsync] (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:74229)
    at r.initializeAndChangeOnce (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:204774)
    at OSF.InitializationHelper.prepareRightBeforeWebExtensionInitialize (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:234160)
    at https://appsforoffice.microsoft.com/lib/1/hosted/office.js:12:12664
    at d (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:12:3420)
    at f.waitForFunction (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:12:3509)
    at d (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:12:12458)
    at OSF.InitializationHelper.loadAppSpecificScriptAndCreateOM (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:233537)
```

Any idea about how to fix this issue?

**Comment by taylorlee** [comment]
I've also run into this. (Outlook Add-In, using Chrome)

**Comment by schmkr** [comment]
Same here. In macOS Safari, the error is:

```
TypeError: null is not an object (evaluating 'OSF.getClientEndPoint().registerForEvent')
```

**Comment by PaulDMendoza** [comment]
Did anyone ever find a solution to this? I'm having the same issue.

**Comment by Katli95** [comment]
Same issue on Outlook in chrome :/

**Comment by Katli95** [comment]
I did some stuff, don't really know which part helped but I believe it was when I allowed localhost in the manifest.xml <App Domains>, I still get the warnings but I can indeed send info back and forth.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
